name: Cache Invalidation
on:
  workflow_run:
    workflows:
      - "pages-build-deployment"
    types: [completed]
jobs:
  cloudflare:
    name: "CloudFlare"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Prod
        uses: actions/checkout@v2
        with:
           ref: production
      - name: "Invalidate the cache"
        shell: bash
        run: |
          echo "Identifying URLs to purge..."
          URLS=$(git ls-files -z | jq -Rs 'split("\u0000")' | sed 's\ "\ "https://buddhistuniversity.net/patanjali-yoga-sutra/\g' | sed 's\/index.html"\/"\g' | sed 's\.html"\"\g')
          echo "Hitting the CloudFlare API..."
          HTTP_RESPONSE=$(curl -sSX POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache" -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" -H "Content-Type:application/json" -w "HTTP_STATUS:%{http_code}" --data "{\"files\":${URLS}}")
          HTTP_BODY=$(echo "${HTTP_RESPONSE}" | sed -E 's/HTTP_STATUS\:[0-9]{3}$//')
          HTTP_STATUS=$(echo "${HTTP_RESPONSE}" | tr -d '\n' | sed -E 's/.*HTTP_STATUS:([0-9]{3})$/\1/')
          if [ "${HTTP_STATUS}" -eq "200" ]; then
            SUCCESS=$(echo ${HTTP_BODY} | python3 -c "import sys, json;print(json.load(sys.stdin)['success'])")
            if [ "${SUCCESS}" = "True" ]; then
              echo "Successfully purged!"
              echo "::group::Raw response"
              echo "${HTTP_BODY}"
              echo "::endgroup::"
              exit 0
            else
              echo "Unsuccessful purge!"
              echo "API response was:"
              echo "${HTTP_BODY}"
              exit 1
            fi
          else
            echo "Request failed. API response was ($HTTP_STATUS): "
            echo "${HTTP_BODY}"
            exit 1
          fi
